name: "Hetzner DNS Updater"
description: >
  Use the Hetzner DNS API to update IPs of given domains. 
  The external IP is retrieved from a given entity cotaining the IP address
version: "1.0.0"
slug: "hetzner-dns"
init: false
hassio_api: true
homeassistant_api: true
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  url: "https://dns.hetzner.com/api/v1/"
  token: ""
  ip_entity: ""
  domains: ""
schema:
  url: str
  token: password
  ip_entity: str
  domains:
    - match(^@\.([A-Za-z0-9\-]{1,63}\.)*[A-Za-z0-9\-]{1,63}$|^(?!-)[A-Za-z0-9\-]{1,63}(\.[A-Za-z0-9\-]{1,63})*\.?$)
