name: "Hetzner DNS Updater"
description: "Use the Hetzner DNS API to update IPs of given domains."
version: "dev"
slug: "hetzner-dns"
init: false
uart: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: "INFO"
  host: "core-mosquitto"
  port: 1883
  username: ""
  password: ""
  keepalive: 60
schema:
  log_level: list(NOTSET|DEBUG|INFO|WARNING|ERROR|CRITICAL)
  host: str
  username: str
  token: password
  port: port
  keepalive: int
