name: "Hetzner DNS Updater"
description: "Use the Hetzner DNS API to update IPs of given domains."
version: "dev"
slug: "hetzner-dns"
init: false
uart: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  url: "https://dns.hetzner.com/api/v1/"
  token: ""
  ip_entity: "list-of-entities"
  domains: ""
schema:
  url: str
  token: password
  ip_entity: device(subsystem=tty)
  domains:
    - match(^(?=.{1,255}$)(?!-)[A-Za-z0-9\-]{1,63}(\.[A-Za-z0-9\-]{1,63})*\.?(?<!-)$)
